import { strict as assert } from "node:assert";
import { test } from "node:test";
import * as errors from "../src/errors.js";
import { ParseError, RegistrationError } from "../src/errors.js";

// Every expected string below was generated by running the corresponding Go
// template from go/strictcli/errors.go through fmt.Sprintf/fmt.Errorf with
// the same arguments -- the assertions pin byte-identical output.

// --- Catalog census ---

// Reconciliation against the conformance parity extractor
// (conformance/check_error_parity.py run against go/strictcli/errors.go):
// extract_go_errors yields 222 raw templates (200 func bodies + 22 consts),
// deduplicating to 219 unique normalized signatures. errors.ts exports one
// template function per raw Go template, hence 222, plus 4 templates with no
// errors.go body: errTagContractViolation (inline fmt.Sprintf in strictcli.go
// / Python _validate_tag_contracts), errHandlerReturnInvalid (Python
// _interpret_handler_return; inexpressible in Go), errOutcomeExitCodeNotInteger
// (TS-only factory guard), and errCommandFlagRelativeToRootUndeclared (Python
// _build_and_validate_command; Go validates markers with no command context).
// The config subphase adds 9 more with no errors.go body: 5 TOML-1.0
// acceptance-gate templates and 2 splice-verification templates (TS-only; the
// siblings' TOML parsers are 1.0-native), plus errAppConfigFormatBad and
// errAppConfigConflictModeBad (inline f-strings in Python App.__post_init__ /
// inline panics in Go option constructors).
// The checks subphase adds 1 more with no errors.go body:
// errCheckOutcomeDirectConstruction (Python _CheckOutcome.__post_init__ mint
// guard; Go seals the outcome structurally with unexported fields).
// The invoke/tool/MCP subphase adds 2 more with no errors.go body:
// errCallPathIsGroup (Python call() group-path message; Go inlines "no
// command resolved from path" in invoke.go) and errRouterCommandMustBeString
// (inline InvokeError literal in Go makeRouterTool / Python router execute).
// The error-parity task (6.4) centralizes 26 formerly-inline Python-wording
// templates with no errors.go body (Go's counterparts are inline or use
// different wording): 12 dict-flag parse templates + 2 positional-arg
// wrappers (values.ts), 9 registration templates (factories.ts), and 3
// check-provider materialization guards (app.ts / checks/provider.ts).
const EXPECTED_TEMPLATE_COUNT = 264;

function templateFunctions(): [string, (...args: never[]) => unknown][] {
	// Widen to unknown first: the module also exports the two error classes,
	// whose constructor types break a direct function-shaped type predicate.
	const entries: [string, unknown][] = Object.entries(errors);
	return entries.filter(
		(entry): entry is [string, (...args: never[]) => unknown] =>
			entry[0].startsWith("err") && typeof entry[1] === "function",
	);
}

test("catalog exports exactly the extractor's template count", () => {
	assert.equal(templateFunctions().length, EXPECTED_TEMPLATE_COUNT);
});

test("template function names are unique and follow errXxx naming", () => {
	const names = templateFunctions().map(([name]) => name);
	assert.equal(new Set(names).size, names.length);
	for (const name of names) {
		assert.match(name, /^err[A-Z]/);
	}
});

test("every template returns a non-empty string for dummy args", () => {
	// Max template arity is 4. Number-typed slots interpolate string dummies
	// just as well for the non-emptiness check.
	for (const [name, fn] of templateFunctions()) {
		const out = (fn as (...args: unknown[]) => unknown)("a", "b", "c", "d");
		assert.equal(typeof out, "string", name);
		assert.ok((out as string).length > 0, name);
	}
});

// --- Byte-parity samples: parse-time section templates ---

test("parse-time templates are byte-identical to sibling output", () => {
	assert.equal(errors.errUnknownFlag("--unknown"), "unknown flag '--unknown'");
	assert.equal(
		errors.errFlagInvalidChoice("format", "xml", "text, json"),
		"--format: invalid value 'xml', must be one of: text, json",
	);
	assert.equal(
		errors.errArgInvalidChoice("mode", "fast", "slow, safe"),
		"argument 'mode': invalid value 'fast', must be one of: slow, safe",
	);
	assert.equal(errors.errUnknownCommand("deploy"), "unknown command 'deploy'");
	assert.equal(
		errors.errUnknownCommandInGroup("push", "myapp remote"),
		"unknown command 'push' in 'myapp remote'",
	);
	assert.equal(
		errors.errMissingRequiredArgument("target"),
		"missing required argument 'target'",
	);
	assert.equal(
		errors.errUnexpectedArgument("extra"),
		"unexpected argument 'extra'",
	);
	assert.equal(
		errors.errCommandDeprecated("old-cmd", "use 'new-cmd' instead"),
		"command 'old-cmd' is deprecated: use 'new-cmd' instead",
	);
	assert.equal(
		errors.errBoolFlagNoValue("--verbose"),
		"flag '--verbose' is a boolean flag and does not take a value",
	);
	assert.equal(
		errors.errBoolNegationNoValue("--no-verbose"),
		"flag '--no-verbose' is a boolean negation and does not take a value",
	);
	assert.equal(
		errors.errFlagRequiresValue("--target"),
		"flag '--target' requires a value",
	);
	assert.equal(
		errors.errFlagDuplicateValue("tag", "web"),
		"--tag: duplicate value 'web'",
	);
	assert.equal(
		errors.errInvalidBoolEnvValue("maybe", "MYAPP_VERBOSE", "verbose"),
		"invalid boolean value 'maybe' for env var 'MYAPP_VERBOSE' (flag '--verbose')",
	);
	assert.equal(
		errors.errMutuallyExclusive("--json, --quiet"),
		"--json, --quiet are mutually exclusive",
	);
	assert.equal(
		errors.errOneOfRequired("--json, --quiet"),
		"one of --json, --quiet is required",
	);
	assert.equal(
		errors.errFlagRequiresFlag("watch", "serve"),
		"flag '--watch' requires '--serve'",
	);
	assert.equal(
		errors.errFlagsMustBeUsedTogether("--user, --pass"),
		"flags --user, --pass must be used together",
	);
	assert.equal(
		errors.errImpliesConflict("push", "", "commit", "no-"),
		"flag '--push' implies '--commit', but '--no-commit' was explicitly provided",
	);
	assert.equal(
		errors.errHermeticConfigMutuallyExclusive(),
		"--hermetic and --config are mutually exclusive",
	);
	assert.equal(
		errors.errWrappedFromEnvVar("expected integer, got 'x'", "MYAPP_COUNT"),
		"expected integer, got 'x' (from env var 'MYAPP_COUNT')",
	);
	assert.equal(
		errors.errFlagErrFromEnvVar(
			"count",
			"expected integer, got 'x'",
			"MYAPP_COUNT",
		),
		"--count: expected integer, got 'x' (from env var 'MYAPP_COUNT')",
	);
	assert.equal(
		errors.errAtPrefixFileNotFound("body", "/tmp/missing.txt"),
		"--body: file not found: /tmp/missing.txt",
	);
	assert.equal(errors.errNoCommandSpecified(), "no command specified");
	assert.equal(
		errors.errFlagSetInBothCliAndConfig("verbose"),
		"flag 'verbose' set in both cli and config; remove one",
	);
});

// --- Byte-parity samples: strict scalar parsing templates ---
// (Section "parse.go — strict parsing" carries no "(parse-time)" marker
// because these are wrapped with a flag/arg prefix at their call sites.)

test("strict scalar parsing templates are byte-identical to sibling output", () => {
	assert.equal(errors.errExpectedInteger("abc"), "expected integer, got 'abc'");
	assert.equal(
		errors.errExpectedBoolean("maybe"),
		"expected boolean, got 'maybe'",
	);
	assert.equal(errors.errExpectedFloat("1.2.3"), "expected float, got '1.2.3'");
	assert.equal(errors.errNaNNotAllowed(), "NaN is not allowed");
	assert.equal(errors.errInfNotAllowed(), "Inf is not allowed");
});

// --- Byte-parity samples: registration-time section templates ---

test("registration templates are byte-identical to sibling output", () => {
	assert.equal(
		errors.errInvalidTagName("My Tag"),
		'invalid tag name "My Tag": must match [a-z][a-z0-9-]*',
	);
	assert.equal(
		errors.errFlagForceReserved(),
		"flag 'force' is a reserved name; use a qualified name like 'force-overwrite' or 'force-delete'",
	);
	assert.equal(
		errors.errFlagNoPrefixReserved("no-commit"),
		"flag 'no-commit': names starting with 'no-' are reserved for the negation system; use a positive name instead",
	);
	assert.equal(
		errors.errCommandMutexMinFlags("deploy", 1),
		'command "deploy": mutex group must have at least 2 flags, got 1',
	);
	assert.equal(
		errors.errFlagRepeatableIncompatibleBool("verbose"),
		'Flag "verbose": repeatable is incompatible with type=bool',
	);
	assert.equal(
		errors.errArgListTypeRequiresVariadic("files"),
		'Arg "files": list type requires variadic=true',
	);
	assert.equal(
		errors.errArgDefaultNotInChoices("mode", "fast", "slow, safe"),
		"Arg \"mode\": default 'fast' is not in choices [slow, safe]",
	);
	assert.equal(
		errors.errGroupCollidesWithCommand("remote"),
		'group "remote" collides with an existing command',
	);
	assert.equal(
		errors.errChecksTomlMissingApp(),
		'checks.toml: missing required top-level key "app"',
	);
	assert.equal(
		errors.errChecksTomlSeverityInvalid("lint", "critical"),
		'checks.toml: check "lint": "severity" must be "error" or "warn", got "critical"',
	);
	assert.equal(
		errors.errCommandEnvVarPrefix("build", "TARGET", "target", "MYAPP_"),
		'command "build": env var "TARGET" for flag "target" must start with "MYAPP_" (or set prefixed=false)',
	);
	assert.equal(errors.errAppHelpEmpty(), "App.help must be a non-empty string");
	assert.equal(
		errors.errWithConfigConflictModeBadMode("both"),
		'WithConfigConflictMode: mode must be "cli-wins" or "error", got "both"',
	);
	assert.equal(
		errors.errDuplicateGlobalFlag("verbose"),
		'duplicate global flag name "verbose"',
	);
	assert.equal(
		errors.errCheckSeverityMismatch(
			"lint",
			"warn",
			"RegisterCheck",
			"RegisterWarnCheck",
		),
		'check "lint": declared severity "warn" in checks.toml but registered via RegisterCheck; use RegisterWarnCheck',
	);
	assert.equal(
		errors.errFlagDefaultElementError("ports", 2, "expected integer, got 'x'"),
		"Flag \"ports\": default element 2: expected integer, got 'x'",
	);
	assert.equal(
		errors.errTagExprUnexpectedChar("@", 5),
		'tag expression: unexpected character "@" at position 5',
	);
	assert.equal(
		errors.errConfigFieldNameInvalid("Bad.Name"),
		'ConfigField name "Bad.Name" is invalid: must match [a-z][a-z0-9_]*(.[a-z][a-z0-9_]*)* (lowercase, dots for sections)',
	);
	assert.equal(
		errors.errSchemaMismatch("old-proj", "new-proj"),
		"Schema mismatch: existing schema belongs to project 'old-proj', not 'new-proj'. Run from the correct project directory.",
	);
});

// --- Go %q (strconv.Quote) edge cases, verified against Go output ---

test("%q slots quote exactly like Go strconv.Quote", () => {
	assert.equal(
		errors.errInvalidTagName('a"b'),
		'invalid tag name "a\\"b": must match [a-z][a-z0-9-]*',
	);
	assert.equal(
		errors.errInvalidTagName("a\\b"),
		'invalid tag name "a\\\\b": must match [a-z][a-z0-9-]*',
	);
	assert.equal(
		errors.errInvalidTagName("a\tb"),
		'invalid tag name "a\\tb": must match [a-z][a-z0-9-]*',
	);
	assert.equal(
		errors.errInvalidTagName("a\nb"),
		'invalid tag name "a\\nb": must match [a-z][a-z0-9-]*',
	);
	assert.equal(
		errors.errInvalidTagName("a\x01b"),
		'invalid tag name "a\\x01b": must match [a-z][a-z0-9-]*',
	);
	assert.equal(
		errors.errInvalidTagName("café"),
		'invalid tag name "café": must match [a-z][a-z0-9-]*',
	);
});

// --- Error classes ---

test("RegistrationError carries only a message", () => {
	const e = new RegistrationError("boom");
	assert.ok(e instanceof Error);
	assert.ok(e instanceof RegistrationError);
	assert.equal(e.name, "RegistrationError");
	assert.equal(e.message, "boom");
});

test("ParseError carries only a message", () => {
	const e = new ParseError("bad flag");
	assert.ok(e instanceof Error);
	assert.ok(e instanceof ParseError);
	assert.equal(e.name, "ParseError");
	assert.equal(e.message, "bad flag");
});

test("the two error classes are distinct", () => {
	assert.ok(!(new ParseError("x") instanceof RegistrationError));
	assert.ok(!(new RegistrationError("x") instanceof ParseError));
});
