[[projects]]
path = "python/"
name = "strictcli"

[[projects]]
path = "go/"
name = "go-strictcli"

[[projects]]
path = "conformance/"
name = "conformance"
internal = true
watch = ["python/**", "go/**"]
